# SPDX-FileCopyrightText: 2023 Peter Lemenkov <lemenkov@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: codespell
on: [push, pull_request]
permissions: {}
jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          skip: ./.git, ./COPYING, ./COPYING.LIB, ./LICENSES
