# SPDX-FileCopyrightText: 2022 Peter Lemenkov <lemenkov@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Testing on Linux

on:
  push:
    branches:
         - '*'
  pull_request:
    branches:
         - '*'
env:
  DEB_DH_SHLIBDEPS_ARGS_ALL: "--dpkg-shlibdeps-params=--ignore-missing-info"

  workflow_dispatch:

jobs:
  build_all:
    strategy:
      matrix:
        os:
          - runs-on: ubuntu-22.04
          - runs-on: ubuntu-24.04
    runs-on: ${{ matrix.os.runs-on }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      # Runs a single command using the runners shell
      - name: build and run tests packages with all featured readers
        run: |
            sudo apt update
            sudo apt install -y gcc g++ libgraphicsmagick1-dev libpng-dev libexiv2-dev libtiff-dev libjpeg-dev libxml2-dev libbz2-dev libfreetype6-dev libpstoedit-dev autoconf automake libtool intltool autopoint
            ./autogen.sh
            ./configure
            make
            make check

  build_with_latest_imagemagick_6:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      # Runs a single command using the runners shell
      - name: build and run tests package against ImageMagick 6 only
        run: |
            sudo apt update
            sudo apt install -y gcc g++ libmagickcore-6.q16-dev libpng-dev libexiv2-dev libtiff-dev libjpeg-dev libxml2-dev libbz2-dev libfreetype6-dev libpstoedit-dev autoconf automake libtool intltool autopoint
            ./autogen.sh
            ./configure --enable-magick-readers
            make
            make check

  build_with_latest_imagemagick_7:
    runs-on: ubuntu-latest
    container: fedora:42
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      # Runs a single command using the runners shell
      - name: build and run tests package against ImageMagick 7 only
        run: |
            sudo dnf update -y
            sudo dnf install -y ImageMagick-devel autoconf automake gcc gcc-c++ gettext-devel glib2-devel intltool libpng-devel libstdc++-devel libtiff-devel libtool make pkgconf-pkg-config procps-ng pstoedit-devel which
            ./autogen.sh
            ./configure --enable-magick-readers
            make
            make check

  build_with_latest_graphicsmagick:
    runs-on: ubuntu-latest
    container: fedora:42
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      # Runs a single command using the runners shell
      - name: build and run tests package against GraphicsMagick only
        run: |
            sudo dnf update -y
            sudo dnf install -y GraphicsMagick-devel autoconf automake gcc gcc-c++ gettext-devel glib2-devel intltool libpng-devel libstdc++-devel libtiff-devel libtool make pkgconf-pkg-config procps-ng pstoedit-devel which
            ./autogen.sh
            ./configure --enable-magick-readers
            make
            make check

  build_with_pstoedit_4_00:
    runs-on: ubuntu-latest
    container: fedora:42
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      # Runs a single command using the runners shell
      - name: build and run tests package against pstoedit 4.00
        run: |
            sudo dnf update -y
            sudo dnf install -y ImageMagick-devel autoconf automake gcc gcc-c++ gettext-devel glib2-devel intltool libpng-devel libstdc++-devel libtiff-devel libtool make pkgconf-pkg-config procps-ng pstoedit-devel which
            ./autogen.sh
            ./configure --enable-magick-readers
            make
            make check
