# SPDX-FileCopyrightText: 2022 Peter Lemenkov <lemenkov@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Testing on Mac OS X

on:
  push:
    branches: [master]

env:
  workflow_dispatch:

jobs:
  build_with_graphicsmagick:
    runs-on: macOS-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      # Runs a single command using the runners shell
      - name: build and run tests packages with all featured readers
        run: |
            brew update
            # Required for intltool and you cannot just brew install perl-xml-parser (formulae broken?)
            perl -MCPAN -e "install XML::Parser"
            perl -e "require XML::Parser"
            brew install graphicsmagick pstoedit libpng gettext intltool glib libtool autoconf automake pkg-config
            ./autogen.sh
            ./configure
            make
            make check
        shell: bash
