# SPDX-FileCopyrightText: 2022 Peter Lemenkov <lemenkov@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Testing on Mac OS X

on:
  push:
    branches: [master]

env:
  workflow_dispatch:

jobs:
  build_all:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: build and run tests packages with all featured readers
        run: |
            brew update
            perl -MCPAN -e "install XML::Parser"
            perl -e "require XML::Parser"
            for pkg in graphicsmagick pstoedit libpng exiv2 libtiff libjpeg libxml2 bzip2 freetype gettext intltool glib libtool autoconf automake pkg-config; do brew install $pkg || brew upgrade $pkg; done
            ./autogen.sh
            ./configure
            make
            make check
        shell: bash
