# This is a basic workflow to help you get started with Actions

name: Testing on Mac OS X

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]

env:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_with_graphicsmagick:
    runs-on: macOS-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      # Runs a single command using the runners shell
      - name: build and run tests packages with all featured readers
        run: |
            brew update
            # Required for intltool and you cannot just brew install perl-xml-parser (formulae broken?)
            perl -MCPAN -e "install XML::Parser"
            perl -e "require XML::Parser"
            brew install graphicsmagick pstoedit libpng gettext intltool glib libtool autoconf automake pkg-config
            ./autogen.sh
            ./configure
            make
            make check
        shell: bash
