# SPDX-FileCopyrightText: 2024 Peter Lemenkov <lemenkov@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Building for Windows

on:
  push:
    tags:
      - '*'           # Push events to every tag not containing /

env:
  DEB_DH_SHLIBDEPS_ARGS_ALL: "--dpkg-shlibdeps-params=--ignore-missing-info"

jobs:
  build_win32_64_installer:
    runs-on: ubuntu-latest
    container: fedora:38
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      # Runs a single command using the runners shell
      - name: Install all dependencies for Win32 and Win64
        run: |
            sudo dnf update -y
            sudo dnf install -y autoconf automake gettext-devel glib2-devel intltool libtool make mingw32-filesystem mingw32-glib2 mingw32-libpng mingw32-gcc mingw32-nsis mingw64-filesystem mingw64-glib2 mingw64-libpng mingw64-gcc mingw64-nsis pkgconf-pkg-config which
            mkdir -p distribute/win/3rdparty

      - name: Regenerate common ./configure script
        run: ./autogen.sh

      - name: Cross-compile and make installer for Win32
        run: |
            mingw32-configure --without-magick --without-pstoedit
            make

            # Install dependencies
            for dll in iconv.dll libffi-8.dll libgcc_s_dw2-1.dll libglib-2.0-0.dll libgobject-2.0-0.dll libintl-8.dll libpcre2-8-0.dll libpng16-16.dll libwinpthread-1.dll zlib1.dll
            do
              cp -afv /usr/i686-w64-mingw32/sys-root/mingw/bin/$dll distribute/win/3rdparty/$dll
            done

            makensis -DVERSION=${{ github.ref_name }}-$(date +%Y%m%d) -DFLAVOUR=win32 distribute/win/autotrace.nsi
            ls -la distribute/win

      - name: Cross-compile and make installer for Win64
        run: |
            mingw64-configure --without-magick --without-pstoedit
            make

            # Install dependencies
            for dll in iconv.dll libffi-8.dll libglib-2.0-0.dll libgobject-2.0-0.dll libintl-8.dll libpcre2-8-0.dll libpng16-16.dll zlib1.dll
            do
              cp -afv /usr/x86_64-w64-mingw32/sys-root/mingw/bin/$dll distribute/win/3rdparty/$dll
            done

            makensis -DVERSION=${{ github.ref_name }}-$(date +%Y%m%d) -DFLAVOUR=win32 distribute/win/autotrace.nsi
            ls -la distribute/win

      - uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: distribute/win/autotrace-*-setup.exe
